# Generated by Django 5.0.1 on 2024-01-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='text',
        ),
    ]
